### PR TITLE
release: 0.4.0

### LINKED ISSUE #6: MySQL support
I plan to add MySQL support to give the package feature parity with Kysely.

### LINKED ISSUE #9: CLI throwing error for any command
I am trying to test `kysely-codegen` with SQLite but the CLI keeps throwing `Cannot find module 'pg'` for any commands that I pass it.
<details>
  <summary>Click to expand!</summary>
  
  ```bash
    > pnpm kysely-codegen --dialect sqlite
    node:internal/modules/cjs/loader:936
      throw err;
      ^
    
    Error: Cannot find module 'pg'
    Require stack:
    - /home/woody88/Code/Typescript/meetapp/node_modules/.pnpm/kysely-codegen@0.3.0_eb47a1c54283209bc69ae17fc7e73157/node_modules/kysely-codegen/dist/dialects/postgres.js
    - /home/woody88/Code/Typescript/meetapp/node_modules/.pnpm/kysely-codegen@0.3.0_eb47a1c54283209bc69ae17fc7e73157/node_modules/kysely-codegen/dist/dialect-manager.js
    - /home/woody88/Code/Typescript/meetapp/node_modules/.pnpm/kysely-codegen@0.3.0_eb47a1c54283209bc69ae17fc7e73157/node_modules/kysely-codegen/dist/cli.js
        at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
        at Function.Module._load (node:internal/modules/cjs/loader:778:27)
        at Module.require (node:internal/modules/cjs/loader:1005:19)
        at require (node:internal/modules/cjs/helpers:102:18)
        at Object.<anonymous> (/home/woody88/Code/Typescript/meetapp/node_modules/.pnpm/kysely-codegen@0.3.0_eb47a1c54283209bc69ae17fc7e73157/node_modules/kysely-codegen/dist/dialects/postgres.js:5:14)
        at Module._compile (node:internal/modules/cjs/loader:1103:14)
        at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
        at Module.load (node:internal/modules/cjs/loader:981:32)
        at Function.Module._load (node:internal/modules/cjs/loader:822:12)
        at Module.require (node:internal/modules/cjs/loader:1005:19) {
      code: 'MODULE_NOT_FOUND',
      requireStack: [
        '/home/woody88/Code/Typescript/meetapp/node_modules/.pnpm/kysely-codegen@0.3.0_eb47a1c54283209bc69ae17fc7e73157/node_modules/kysely-codegen/dist/dialects/postgres.js',
        '/home/woody88/Code/Typescript/meetapp/node_modules/.pnpm/kysely-codegen@0.3.0_eb47a1c54283209bc69ae17fc7e73157/node_modules/kysely-codegen/dist/dialect-manager.js',
        '/home/woody88/Code/Typescript/meetapp/node_modules/.pnpm/kysely-codegen@0.3.0_eb47a1c54283209bc69ae17fc7e73157/node_modules/kysely-codegen/dist/cli.js'
      ]
    }
  ```
</details>

### LINKED ISSUE #10: Add schema support
I have schemas other than public.

### PR DESCRIPTION
**Pull request by RobinBlomberg**
```
npm install -D kysely-codegen@0.4.0-beta.2
```

Closes #6, closes #8, closes #9, closes #10 and closes #11.

Features a massive rewrite of the codebase, and adds many new features and improvements.

Incorporates contributions/ideas from [koskimas](https://github.com/koskimas) (#11) and [DavesBorges](https://github.com/DavesBorges) (#8), and suggestions from [thdxr](https://github.com/thdxr). The big rewrites made it hard to merge the pull requests directly, but I've tried to add in many of the changes manually. In the future, I will avoid large refactors and try to ensure that all commits focus on specific features and issues.

### Notable changes

- build: make kysely a peer dependency
- build: upgrade modules
- feat!: make generated PostgreSQL and SQLite types more accurate
- feat: add MySQL support
- feat: add PostgreSQL schema support
- feat: lazy load database drivers
- feat: make adapters separable from their dialects
- feat: make dialect CLI option optional (automatically inferred)
- refactor!: remove format CLI option
- refactor: implement new AST-based transformer/serializer
- refactor: export internal modules and make them dependency-injectable
- test: add tests

### CODE REVIEW

File: src/transformer.ts [hunk 1]
```diff
@@ -0,0 +1,236 @@
...
+  constructor(dialect: Dialect) {
+    this.#declarationNodes = [];
+    this.#defaultType =
+      dialect.adapter.defaultType ?? new IdentifierNode('unknown');
+    this.#definitions = { ...DEFINITIONS, ...dialect.adapter.definitions };
+    this.#dialect = dialect;
+    this.#exportedProperties = [];
+    this.#imported = {};
+    this.#imports = { ColumnType: 'kysely', ...dialect.adapter.imports };
+    this.#symbols = SYMBOLS;
```
Comment (koskimas) [inline src/transformer.ts:46]: This should be

```ts
this.#symbols = { ...SYMBOLS };
```

otherwise you end up modifying the global `SYMBOLS` list and any subsequently created instance of `Transformer` will get the previously added symbols (by `#declareSymbol`) by default.

Comment (RobinBlomberg) [reply src/transformer.ts]: Ahh, good catch! Thank you — fixed!
