### PR TITLE
Fix Postgres JSON type

### LINKED ISSUE #124: The generated `type Json = ColumnType<JsonValue, string, string>` should just be `JsonValue` for Postgres.
If I'm not mistaken, the generated json type `type Json = ColumnType<JsonValue, string, string>` seems to be overly restrictive for Postgres, as I can use kysely to insert and update `JsonValue` values, in addition to strings. Since `JsonValue | string` is just `JsonValue`, the whole thing can be collapsed `type Json = JsonValue`.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/RobinBlomberg) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/RobinBlomberg/kysely-codegen/issues/124">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/RobinBlomberg/kysely-codegen/issues/124/pledge.svg?darkmode=1">
  Fund with Polar
</picture>
</a>

### PR DESCRIPTION
**Pull request by BoscoDomingo**
The JSON type for Postgres was wrong, as it accepts a JSON itself directly via Kysely for insertion and update, no need to convert to string

Fixes #124 

Video showing result:

https://github.com/RobinBlomberg/kysely-codegen/assets/46006784/51862d76-cc47-43da-85d9-adf9a820b07a

### CODE REVIEW

**Comment by BoscoDomingo** [comment]
@RobinBlomberg Would love this to be checked 🙏🏼

File: src/transformer/definitions.ts [hunk 1]
```diff
@@ -78,3 +78,5 @@ export const JSON_VALUE_DEFINITION: DefinitionNode = new UnionExpressionNode([
   new IdentifierNode('JsonObject'),
   new IdentifierNode('JsonPrimitive'),
 ]);
+
+export const JSON_DEFINITION: DefinitionNode =new IdentifierNode('JsonValue');
```
Comment (elitan) [inline src/transformer/definitions.ts:82]:
```suggestion
export const JSON_DEFINITION: DefinitionNode = new IdentifierNode('JsonValue');
```

**Review by elitan — APPROVED** [review]

**Comment by RobinBlomberg** [comment]
Great! Thanks for the fix!
