### PR TITLE
Deterministic code generation fix

### LINKED ISSUE #96: Deterministic code generation fix
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `kysely-codegen@0.10.1` for the project I'm working on.

We are having some failing CICD checks because when using the code generation CLI, columns are generated in different orders in some tables when run in CICD vs locally, which creates some file diffs and fails the tests. This code will sort fields before generating the file code.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/kysely-codegen/dist/serializer.js b/node_modules/kysely-codegen/dist/serializer.js
index 8e0df3a..381f808 100644
--- a/node_modules/kysely-codegen/dist/serializer.js
+++ b/node_modules/kysely-codegen/dist/serializer.js
@@ -10,6 +10,7 @@ class Serializer {
     constructor(options = {}) {
         this.typeOnlyImports = options.typeOnlyImports ?? true;
     }
+
     serialize(nodes) {
         let data = '';
         let i = 0;
@@ -191,7 +192,14 @@ class Serializer {
         data += '{';
         if (node.properties.length) {
             data += '\n';
-            for (const property of node.properties) {
+
+            const orderedNodes = node.properties.sort((a, b) => {
+              if (a.key < b.key) return -1;
+              if (a.key > b.key) return 1;
+              return 0;
+            });
+
+            for (const property of orderedNodes) {
                 data += '  ';
                 data += this.serializeProperty(property);
             }
@@ -210,13 +218,25 @@ class Serializer {
     serializeUnionExpression(node) {
         let data = '';
         let i = 0;
-        for (const arg of node.args) {
+
+        const orderedArgs = node.args.sort((a, b) => {
+          if(a.type !== NodeType.IDENTIFIER || b.type !== NodeType.IDENTIFIER) return 0
+          const last =  ['undefined', 'null']
+          if (last.includes(a.name)) return 1
+          if (last.includes(b.name)) return -1
+          if (a.name < b.name) return -1;
+          if (a.name > b.name) return 1;
+          return 0;
+        });
+
+        for (const arg of orderedArgs) {
             if (i >= 1) {
                 data += ' | ';
             }
             data += this.serializeExpression(arg);
             i++;
         }
+
         return data;
     }
 }
diff --git a/node_modules/kysely-codegen/src/serializer.ts b/node_modules/kysely-codegen/src/serializer.ts
index 72f1786..86360b6 100644
--- a/node_modules/kysely-codegen/src/serializer.ts
+++ b/node_modules/kysely-codegen/src/serializer.ts
@@ -280,7 +280,14 @@ export class Serializer {
     if (node.properties.length) {
       data += '\n';
 
-      for (const property of node.properties) {
+      const orderedNodes = node.properties.sort((a, b) => {
+        if (a.key < b.key) return -1;
+        if (a.key > b.key) return 1;
+        return 0;
+      });
+      
+
+      for (const property of orderedNodes) {
         data += '  ';
         data += this.serializeProperty(property);
       }
@@ -306,7 +313,17 @@ export class Serializer {
     let data = '';
     let i = 0;
     
-    for (const arg of node.args) {
+    const orderedArgs = node.args.sort((a, b) => {
+      if(a.type !== enums_1.NodeType.IDENTIFIER || b.type !== enums_1.NodeType.IDENTIFIER) return 0
+      const last =  ['undefined', 'null']
+      if (last.includes(a.name)) return 1
+      if (last.includes(b.name)) return -1
+      if (a.name < b.name) return -1;
+      if (a.name > b.name) return 1;
+      return 0;
+    });
+
+    for (const arg of orderedArgs) {
       if (i >= 1) {
         data += ' | ';
       }
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

### PR DESCRIPTION
**Pull request by bombillazo**
Fixes #96

### CODE REVIEW

**Comment by bombillazo** [comment]
@RobinBlomberg Any update on this PR?

File: src/serializer.ts [hunk 1]
```diff
@@ -280,7 +280,14 @@ export class Serializer {
     if (node.properties.length) {
       data += '\n';
 
-      for (const property of node.properties) {
+      const orderedNodes = node.properties.sort((a, b) => {
```
Comment (noppa) [inline src/serializer.ts:283]: Random note from a random person randomly taking a look, but this
```javascript
      const orderedNodes = node.properties.sort((a, b) => {
```
looks like the expectation is to create a new sorted array, when it actually doesn't; `.sort` mutates the original. I'm not sure if it's a problem here in practice, but thought I'd point that out since it looks accidental here and could in some cases cause weird bugs elsewhere if the array is expected to be in some other order there.

Comment (bombillazo) [reply src/serializer.ts:283]: Hey, I see no problem; the tests prove the logic is working as intended. Before this change, no ordering check was being done on the nodes themselves anywhere. 

While you are correct that [sort](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort) modifies the array in place, it also returns the sorted array and I'm simply assigning the sorted array to a new variable for easier handling.

**Comment by RobinBlomberg** [comment]
Published in `kysely-codegen@0.11.0`!
